# Generated by Django 5.0.4 on 2024-05-14 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Car label',
                'verbose_name_plural': 'Cars label',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Категория ТС',
                'verbose_name_plural': 'Категории ТС',
            },
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=100, verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Топливо',
                'verbose_name_plural': 'Топливо',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(default=None, null=True, upload_to='movies/', verbose_name='Фото')),
                ('price', models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Цена')),
                ('slug', models.SlugField(blank=True, max_length=150, verbose_name='Url')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец машины')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp3.carname', verbose_name='Cars')),
                ('category', models.ManyToManyField(max_length=100, to='myapp3.category')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='CarShorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movie_shots/', verbose_name='Pictures')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp3.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Short',
                'verbose_name_plural': 'Shorts',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp3.carname')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='genres',
            field=models.ManyToManyField(max_length=100, to='myapp3.genre'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.ManyToManyField(max_length=100, to='myapp3.specifications'),
        ),
    ]
