# Generated by Django 5.0.4 on 2024-05-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category name'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product name'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Client name'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Product'),
        ),
    ]
